name: Trigger Workflow in mdx-dev org

on:
  workflow_dispatch:

jobs:
  trigger-workflow:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger actions Workflow
        uses: peter-evans/repository-dispatch@v2
        with:
          token: ${{ secrets.PAT }}
          repository: 'mdx-dev/QA-Automation'
          event-type: 'workflow-dispatch'
          client-payload: '{"workflow_id": "ui.yml", "ref": "diff"}'
