name: Trigger Workflow in first org

on:
  workflow_dispatch:

jobs:
  trigger-workflow:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger actions Workflow
        uses: peter-evans/repository-dispatch@v2
        with:
          token: ${{ secrets.PAT }}
          repository: 'DXZA091o/zelis-ideathon'
          event-type: 'workflow-dispatch'
          client-payload: '{"workflow_id": "call-docker-build-frontend.yml", "ref": "main"}'
